# Generated by Django 3.2.7 on 2022-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0005_auto_20220526_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('0', 'Company'), ('1', 'User')], default='1', max_length=100),
        ),
    ]
